# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_db:
            entity: { class: MessagerieBundle\Entity\Membre, property: username }
        
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        MessagerieBundle\Entity\Membre:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_MANAGER:       [ROLE_USER]
        ROLE_ADMIN:       [ROLE_MANAGER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_db
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~


            form_login:
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
                login_path: app_login
                check_path: app_login_check
                success_handler: authentication_handler

            logout:
                path: /logout
                target: /
            
            remember_me:
                secret: "%secret%"
                lifetime: 2232000
                path: /
                remember_me_parameter: "_remember_me"
                always_remember_me: false

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
