<?php

namespace Msg\MessagerieBundle\Repository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends \Doctrine\ORM\EntityRepository
{
	public function myFindAll()
	{
		return $this->createQueryBuilder('a')
		->getQuery()
		->getResult();
	}

}
